### ISSUE TITLE
Duplex connction shows as NONE in OnClientConnectedAction 

### ISSUE THREAD

**Issue by MagicAndre1981** [SignalGo/SignalGo-full-net#12]
I call `serverProvider.ServerDataProvider.GetInformation()` in `serverProvider.OnClientConnectedAction = (client) => {}` and `serverProvider.OnClientDisconnectedAction = (client) => { }` in server to see which client gets connected. In the OnClientConnectedAction I see connection incorrectly as none:

> Client Connected: ClientId: f42537bb-0d0b-45a8-8123-961fc35881f9, IP: ::ffff:192.168.2.113, Client Version: , IsWebSocket: False, ProtocolType: **None**, ConnectedDateTime: 13.06.2019 09:07:35
> serverProvider.ServerDataProvider.GetInformation(): Clients Connected Count: 1
> Http Clients Connected Count: 0
> SignalGoDuplex Clients Connected Count: 0
> SignalGoOneWay Clients Connected Count: 0
> SignalGoStream Clients Connected Count: 0
> WebSocket Clients Connected Count: 0
> None Clients Connected Count: 1

in Disconnect I see correct duplex:

> Client Disconnected: ClientId: f42537bb-0d0b-45a8-8123-961fc35881f9, IP: ::ffff:192.168.2.113, Client Version: , IsWebSocket: False, ProtocolType: **SignalGoDuplex,** ConnectedDateTime: 13.06.2019 09:07:35
> serverProvider.ServerDataProvider.GetInformation(): Clients Connected Count: 0

**Comment by Ali-YousefiTelori** [comment]
because OnClientConnectedAction will call before set protocol type. its about every clients connected for example spam or unkown clients too, for this it will call OnClientConnectedAction before find protocols.

**Comment by MagicAndre1981** [comment]
This also has to be documented to avoid confusion 🙄

**Comment by Ali-YousefiTelori** [comment]
in vertion 6 every systems will changed, logger, actions etc

**Comment by Gerardo-Sista** [comment]
When will version 6 will be ready?
