### ISSUE TITLE
Provide ConnectionState property similar to SignalR

### ISSUE THREAD

**Issue by MagicAndre1981** [SignalGo/SignalGo-full-net#14]
With SignalR you have[ HubConnectionState enum](https://github.com/aspnet/AspNetCore/blob/release/2.2/src/SignalR/clients/csharp/Client.Core/src/HubConnectionState.cs) to check state to see if you are connected.

Please support something similar in your library.

**Comment by Ali-YousefiTelori** [comment]
do you want check client state in client side? or server side?

**Comment by MagicAndre1981** [comment]
Curently I need to write this to check connection state in client:

    _clientProvider.ConnectAsyncAutoReconnect("URL:PORT/SignalGo", ConnectedAction);

     void ConnectedAction(bool b)
     {
          lock (_lockObject)
          {
              _isClientConnected = b;
          }
     }

and check for `_isClientConnected` and call `ConnectAsyncAutoReconnect` again if false.

**Comment by Ali-YousefiTelori** [comment]
No you don't need, in your application ConnectAsyncAutoReconnect must call one time, it will automatically try to connect if disconnected from server, and every time if connection lost or connection successfully your "ConnectedAction" will called with a boolean value that is true or false, true = connected and false = disconnected.

**Comment by MagicAndre1981** [comment]
ok, I just noticed that there is a property `public bool IsConnected { get; internal set; }` to check if connected. Again, without documentation, it is extremely difficult to use your library and find what I look for. 

But I would still prefer an enum with also showing [Reconnecting state like Signal Core 3](https://github.com/aspnet/AspNetCore/blob/release/3.0-preview6/src/SignalR/clients/csharp/Client.Core/src/HubConnectionState.cs#L26)

**Comment by Ali-YousefiTelori** [comment]
use this example:

```csharp
 clientProvider.OnConnectionChanged = (status) =>
            {
                if (status == ConnectionStatus.Connected || status == ConnectionStatus.Reconnected)
                {
                    //connected
                }
                else if (status == ConnectionStatus.Reconnecting)
                {
                    //reconnecting
                }
                else if (status == ConnectionStatus.Disconnected)
                {
                    //disconnected
                }
            };
```
