### ISSUE TITLE
Use Microsoft.Extensions.Logging for Logging

### ISSUE THREAD

**Issue by MagicAndre1981** [SignalGo/SignalGo-full-net#16]
In Version 6, consider usage of the abstract [Microsoft.Extensions.Logging logging](https://blog.stephencleary.com/2018/05/microsoft-extensions-logging-part-1-introduction.html). This allows users to use different Listeners like [Console](https://www.nuget.org/packages/Microsoft.Extensions.Logging.Console/2.2.0), [Debug Output](https://www.nuget.org/packages/Microsoft.Extensions.Logging.Debug/2.2.0), [ETW/Eventsource](https://www.nuget.org/packages/Microsoft.Extensions.Logging.EventSource/2.2.0) or [Windows Eventlog](https://www.nuget.org/packages/Microsoft.Extensions.Logging.EventLog/2.2.0) which is better compared to the [current AutoLogger](https://github.com/SignalGo/SignalGo-full-net/issues/11)

**Comment by Ali-YousefiTelori** [comment]
We are going to use these changes in Easy Microservices packages.
https://github.com/EasyMicroservices
