### ISSUE TITLE
Consider Replacing Json.NET with System.Text.Json in future Version

### ISSUE THREAD

**Issue by MagicAndre1981** [SignalGo/SignalGo-full-net#17]
Microsoft now provides its own JSON library called [System.Text.Json](https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-apis/) which can be consumed on .net standard 2.0 compatible runtimes. 

It should be faster compared to Json.net so consider switching to it in future.

**Comment by Ali-YousefiTelori** [comment]
I'm Working on JsonGo, its very fast and support loop referencing but  System.Text.Json is not support loop referencing.
Json is faster than both of them.

https://github.com/Ali-YousefiTelori/JsonGo

**Comment by Gerardo-Sista** [comment]
Please provide performance comparison. Thank you

**Comment by MagicAndre1981** [comment]
thanks, I was not aware of your own lib. Do you later plan to switch to your library?

**Comment by Ali-YousefiTelori** [comment]
Yes, in version 6 we remove newtonsoft json in signalgo and use JsonGo.

**Comment by MagicAndre1981** [comment]
ok, will this also "fix" the issue [I see here with the ToLocalTime calls](https://github.com/SignalGo/SignalGo-full-net/issues/11#issuecomment-503894536)?

**Comment by Ali-YousefiTelori** [comment]
Yes we will fix all performance issue
