### ISSUE TITLE
Authorize attribute

### ISSUE THREAD

**Issue by larsontim12** [SignalGo/SignalGo-full-net#21]
Is there a way to use an Authorize attribute to the service.  I see the IP limitations but I want to use a user or a token to allow access?

Any example would be great.

Thanks,
Tim

**Comment by Ali-YousefiTelori** [comment]
Hello @larsontim12 and thank you for your issue.

Please read [this document ](https://github.com/SignalGo/SignalGo-full-net/wiki/Authorize-a-client-and-SecurityContractAttribute)in Wiki I wrote for you today. After reading if you had any question I will be ready to answer for you.

Thank you.

**Comment by larsontim12** [comment]
Thank you I Think this gets be what I want to do.  I appreciate the help! -Tim
