### ISSUE TITLE
Where is Expret Context

### ISSUE THREAD

**Issue by larsontim12** [SignalGo/SignalGo-full-net#22]
Looking at the login Method in the Authentication class it shows the ExpertContext and I can't find the reference for this anywhere.  Can you point me to the code?

https://github.com/SignalGo/SignalGo-full-net/wiki/OperationContext-In-Http-Protocol-and-Http-Headers

Thanks,
Tim

**Comment by Ali-YousefiTelori** [comment]
Hello Tim,
The ExpertContext is an EF core database example that is not SignalGo stuff that just shows you how you can do login stuff with your EF Database the main line of SignalGo you have to learn is here:

```csharp
                OperationContext<CurrentUserInfo>.CurrentSetting = new CurrentUserInfo()
                {
                    UserInfo = user,
                    ExpireDateTime = DateTime.Now.AddDays(1),
                    Session = userToken,
                    IsAdmin = user.Id == 1,
                    IsNormalUser = true
                };
```

That shows you how to set your Current user data to SignalGo memory, CurrentUserInfo and UserInfo are the examples you can customize all of them for your self.
OperationContext just need a class and instance to save your data then you can use it later from another method.
