### ISSUE TITLE
Queryable DataExchanger Example

### ISSUE THREAD

**Issue by larsontim12** [SignalGo/SignalGo-full-net#26]
I am trying to run the sample and it is asking for the query as a parameter.  What is a sample query to send and where can I find out more information on what can be sent?

Thanks -Tim

**Comment by Ali-YousefiTelori** [comment]
Hello, @larsontim12 the Signalgo query data exchanger is in preview version yet, if you want to get samples on how to use SignalGo query you can see examples on [Here](https://github.com/SignalGo/SignalGo-full-net/blob/version5/SignalGoTest/DataExhanger/QueryDataExchangerAllTests.cs)

and don't forget to install NuGet package from [Here](https://www.nuget.org/packages/SignalGo.DataExchanger/)

You can use SelectCompiler class to compile your select query then execute query:
```CSharp
            string query = @"select{name family posts{title articles{author}date news{newsName}}files{id name}}var user{where user.family=""yousefi"" and sum ( 5 , 1 , 4 ) == 10)}";
            SelectCompiler selectCompiler = new SelectCompiler();
            string anotherResult = selectCompiler.Compile(query);
```

After compile you can run with your list:
```CSharp
object result = selectCompiler.Run(yourlist);
```

However, you can use ConditionsCompiler for your conditions in your list you can see more examples as I linked you [Here](https://github.com/SignalGo/SignalGo-full-net/blob/version5/SignalGoTest/DataExhanger/QueryDataExchangerAllTests.cs).

**Comment by larsontim12** [comment]
Thank you that is what I needed!
