### ISSUE TITLE
Server Connection SendToAll Clients

### ISSUE THREAD

**Issue by larsontim12** [SignalGo/SignalGo-full-net#29]
I am running 2 server services on the server. One does processing reading and writing data to clients. On service 2 (DataWatcher) is a simple service that will broadcast a SendToAll message to tell any clients listening to service 2 the status.  How can I call the  SendToAll method from the server to update the clients? 

Sorry this maybe a basic question but I haven't been able to figure this out.

Thanks -Tim

**Comment by Ali-YousefiTelori** [comment]
Hello @larsontim12 did you check this documentation? if yes please send me your sample then I will tell you how you can do this.



* **OperationContext And Broadcasting**
    * [Broadcasting System](https://github.com/SignalGo/SignalGo-full-net/wiki/Broadcasting-from-client-to-other-clients-etc.)
    * [OperationContext And Broadcasting](https://github.com/SignalGo/SignalGo-full-net/wiki/OperationContext-and-Broadcasting-and-clients-managements-in-server-side)
    * [OperationContext In Http Protocol and Http Headers](https://github.com/SignalGo/SignalGo-full-net/wiki/OperationContext-In-Http-Protocol-and-Http-Headers)

**Comment by larsontim12** [comment]
I figured it out.  I ended up having something corrupted in the client application that was causing it to hang.  I created a new application and it started working fine.

Thanks -Tim
