### ISSUE TITLE
CDN Source for SignalGo.png

### ISSUE THREAD

**Issue by larsontim12** [SignalGo/SignalGo-full-net#31]
The signalgo package is causing issues in antivirus when opening up nuget screen.  Can you please fix this!

Traffic has been blocked for this application: C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\ENTERPRISE\COMMON7\IDE\DEVENV.EXE

URL: http://cdn.persiangig.com/preview/v14ukL88fq/SignalGo.png
Intensive Protection level: Level 1
URL category: 
	Malicious Sources/Malnets

**Comment by Ali-YousefiTelori** [comment]
@larsontim12 thank you for your issue, I will update SignalGo and fix this (and more fix bugs and new features), the problem happens because nuget has no CDN for uploading packages icons.

**Comment by Ali-YousefiTelori** [comment]
packages updated to new versions and removed persiangig CDN from the nuget.
