### ISSUE TITLE
Using Visual Studio 2022 Extension

### ISSUE THREAD

**Issue by larsontim12** [SignalGo/SignalGo-full-net#32]
In the connected services that is generated by the Visual Studio Extension and it is throwing an error when I try to compile: on  _httpClient.PostHead and  _httpClient.PostHeadAsync.

Do you have a version that has this working or any Ideas?

Thanks,
Tim

public virtual global::SignalGo.Shared.Models.StreamInfo<global::System.DateTime> DownloadProfileImage(int userId, string filePath)
{
        SignalGo.Client.HttpClientResponseBase result = _httpClient.PostHead(_serverUrl + (_serverUrl.EndsWith("/") ? "" : "/") + "teststream/DownloadProfileImage", new SignalGo.Shared.Models.ParameterInfo[]
        {
                 new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(userId),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(userId) },
                 new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(filePath),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(filePath) },
        });
        ResponseHeaders = result.ResponseHeaders;
        Status = result.Status;
        return result.GetStream<global::SignalGo.Shared.Models.StreamInfo<global::System.DateTime>>();
}
public virtual async Task<global::SignalGo.Shared.Models.StreamInfo<global::System.DateTime>> DownloadProfileImageAsync(int userId, string filePath)
{
        SignalGo.Client.HttpClientResponseBase result = await _httpClient.PostHeadAsync(_serverUrl + (_serverUrl.EndsWith("/") ? "" : "/") + "teststream/DownloadProfileImage", new SignalGo.Shared.Models.ParameterInfo[]
        {
                 new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(userId),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(userId) },
                 new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(filePath),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(filePath) },
        });
        ResponseHeaders = result.ResponseHeaders;
        Status = result.Status;
        return result.GetStream<global::SignalGo.Shared.Models.StreamInfo<global::System.DateTime>>();
}

**Comment by Ali-YousefiTelori** [comment]
Hey @larsontim12 
Can you please send me more descriptions?
1. I need Your server-side service (input and output and name) like this:
```csharp
        public async Task<MessageContract<BookResponseContract>> Book([NullOrEmptyValidation] BookRequestContract bookRequest)
```

2. also version of signalgo and signalgo extensions you are using.
3. your service type using ServiceContract attribute

**Comment by Ali-YousefiTelori** [comment]
VSIX version 4.8.1.1 updated and bug fixed.

**Comment by larsontim12** [comment]
Thanks I will try it out.  I see you already fixed it but I was using the C# server and client when it popped up.  I will let you know shortly if it is fixed.

Thanks for the quick response!
Tim

**Comment by Ali-YousefiTelori** [comment]
@larsontim12  Your welcome.
