### ISSUE TITLE
Remove or Upgrade .net framework reference

### ISSUE THREAD

**Issue by SLjavad** [SignalGo/SignalGo-full-net#55]
[SignalGo.Client](https://github.com/SignalGo/SignalGo-full-net/blob/8543ff0bf418cf4f37b4c33be012ec1ed15af566/SignalGo.Client/SignalGo.Client.csproj#L5) and [SignalGo.shared](https://github.com/SignalGo/SignalGo-full-net/blob/8543ff0bf418cf4f37b4c33be012ec1ed15af566/SignalGo.Shared/SignalGo.Shared.csproj#L10) has reference to net4.5
this version of .net framework is deprecated and not supported since 2016
please remove this dependency or update it to the latest version (4.8)
i have some issues in building these two projects because of this dependency

**Comment by Ali-YousefiTelori** [comment]
Hi @SLjavad, Changes pushed to netstandard branch.
