### ISSUE TITLE
Sample usage in .net maui client.

### ISSUE THREAD

**Issue by andylim-mkj** [SignalGo/SignalGo-full-net#56]
Hi,
Do you have any sample on how to use it with an aspnetcore web api and .net maui client?
Thanks.

**Comment by Ali-YousefiTelori** [comment]
Hi @andylim-mkj .

check this example:
https://github.com/Ali-YousefiTelori/WordProjectTranslators

this is the backend and MAUI example.
if you have any question I will be happy to help you.
